apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rockermq-broker-master-a
  finalizers:
    - kubernetes.io/pvc-protection
  namespace: rocketmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem